### PR TITLE
Add support for OxygenOs 2.1.0 (OnePlus Two) + LockPatternUtils Bugfix

### PR DESCRIPTION
**Pull request by ambimanus**
* Add support for OxygenOs 2.1.0 (OnePlus Two),
* bugfix in call to LockPatternUtils

### CODE REVIEW

**Comment by ambimanus** [comment]
Wait, the LockPatternUtils fix may break compatibility to other ROMs... I'll make this more generic and re-open the pull request.

**Comment by LucasR93** [comment]
Another solution may be to check the device's device or model code to apply the correct hook

https://developer.android.com/reference/android/os/Build.html#MODEL
https://developer.android.com/reference/android/os/Build.html#DEVICE

**Comment by ambimanus** [comment]
Thanks for answering.
I tried that, as already mentioned in the comment in the code. Did not work, but I'm unsure why. Will look into that again tomorrow.

**Comment by ambimanus** [comment]
Fixed in #41.

**Pull request closed without merging**
